package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import config.Config;
import javax.swing.JOptionPane;

public class eventoCadastroForm extends javax.swing.JFrame {

    Connection conec = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public eventoCadastroForm() {
    
        conec = config.Config.conectarBD();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entryEventName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entryIngressosDisp = new javax.swing.JTextField();
        eventoDeletarButton = new javax.swing.JButton();
        eventSaveButton = new javax.swing.JButton();
        eventoGerenciarButton = new javax.swing.JButton();
        eventoDeleteButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        entryPrecoBase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inserção de Eventos");

        entryEventName.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryEventName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        entryEventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryEventNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome Evento:");

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingressos Disponíveis");

        entryIngressosDisp.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryIngressosDisp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        entryIngressosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryIngressosDispActionPerformed(evt);
            }
        });

        eventoDeletarButton.setText("Limpar");
        eventoDeletarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventoDeletarButtonMouseClicked(evt);
            }
        });
        eventoDeletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoDeletarButtonActionPerformed(evt);
            }
        });

        eventSaveButton.setText("Salvar");
        eventSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventSaveButtonMouseClicked(evt);
            }
        });

        eventoGerenciarButton.setText("Gerenciar");
        eventoGerenciarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventoGerenciarButtonMouseClicked(evt);
            }
        });

        eventoDeleteButton.setText("Deletar");
        eventoDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventoDeleteButtonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Preço Base");

        entryPrecoBase.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryPrecoBase.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        entryPrecoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryPrecoBaseActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventoDeletarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eventSaveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(entryEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(eventoGerenciarButton)
                                .addGap(18, 18, 18)
                                .addComponent(eventoDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(7, 7, 7)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entryPrecoBase)
                                    .addComponent(entryIngressosDisp))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryEventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryIngressosDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventoDeletarButton)
                    .addComponent(eventSaveButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventoGerenciarButton)
                    .addComponent(eventoDeleteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryEventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryEventNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryEventNameActionPerformed

    private void entryIngressosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryIngressosDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryIngressosDispActionPerformed

    private void eventoDeletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoDeletarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventoDeletarButtonActionPerformed

    private void eventSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventSaveButtonMouseClicked
        cadastrarEvento();
    }//GEN-LAST:event_eventSaveButtonMouseClicked

    private void entryPrecoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryPrecoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryPrecoBaseActionPerformed

    private void eventoDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventoDeleteButtonMouseClicked
        deletarEvento(JOptionPane.showInputDialog(null, "Insira o nome do Evento que deja remover", "Alerta", JOptionPane.INFORMATION_MESSAGE));
    }//GEN-LAST:event_eventoDeleteButtonMouseClicked

    private void eventoGerenciarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventoGerenciarButtonMouseClicked
        buscaEventoForm buscaEvt = new buscaEventoForm();
        buscaEvt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eventoGerenciarButtonMouseClicked

    private void eventoDeletarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventoDeletarButtonMouseClicked
        entryEventName.setText("");
        entryIngressosDisp.setText("");
        entryPrecoBase.setText("");
    }//GEN-LAST:event_eventoDeletarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eventoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eventoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eventoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eventoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eventoCadastroForm().setVisible(true);
            }
        });
    }

    
    public void cadastrarEvento(){
        try{
            String insert  = "INSERT INTO Eventos (nomeEvento, numeroIngressos, precoBase) VALUES (?,?,?)";
            
            pst = conec.prepareStatement(insert);
            
            pst.setString(1, entryEventName.getText());
            pst.setString(2, entryIngressosDisp.getText());
            pst.setString(3, entryPrecoBase.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Evento adicionado com sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } finally{
                    try{
                        rs.close();
                            pst.close();
                    }   catch(Exception e){
                            
                        }
                    }
    }
    
    public void deletarEvento(String d){
        try{
            String deletar = "DELETE FROM Eventos WHERE nomeEvento = ? ";
            pst = conec.prepareStatement(deletar);
            pst.setString(1, d);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Evento deletado permanentememte!");
        
            } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            } finally{
                    try{
                        rs.close();
                            pst.close();
                    }   catch(Exception e){
                            
                        }
                    }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entryEventName;
    private javax.swing.JTextField entryIngressosDisp;
    private javax.swing.JTextField entryPrecoBase;
    private javax.swing.JButton eventSaveButton;
    private javax.swing.JButton eventoDeletarButton;
    private javax.swing.JButton eventoDeleteButton;
    private javax.swing.JButton eventoGerenciarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
