package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import config.Config;
import javax.swing.JOptionPane;

public class ingressoCadastroForm extends javax.swing.JFrame {

    Connection conec = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public ingressoCadastroForm() {
        initComponents();
        
        conec = config.Config.conectarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entryPreco = new javax.swing.JTextField();
        entryNumAssento = new javax.swing.JTextField();
        entryInstituicaoMeia = new javax.swing.JTextField();
        entryCarteiraIdoso = new javax.swing.JTextField();
        entryTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        deleteIngresso = new javax.swing.JButton();
        testbutton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        entryNomeDoEvento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Ingressos");

        entryPreco.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        entryNumAssento.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryNumAssento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNumAssentoActionPerformed(evt);
            }
        });

        entryInstituicaoMeia.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryInstituicaoMeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryInstituicaoMeiaActionPerformed(evt);
            }
        });

        entryCarteiraIdoso.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryCarteiraIdoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryCarteiraIdosoActionPerformed(evt);
            }
        });

        entryTipo.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inteira", "Meia" }));

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel2.setText("N° do Assento");

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel3.setText("Valor Unitário");

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel4.setText("Entrada");

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel5.setText("Instituição Meia");

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel6.setText("N° Carteira Idoso");

        saveButton.setText("Salvar");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        cleanButton.setText("Limpar");
        cleanButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cleanButtonMouseDragged(evt);
            }
        });
        cleanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleanButtonMouseClicked(evt);
            }
        });

        changeButton.setText("Busca/Atualizar");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeButtonMouseClicked(evt);
            }
        });

        deleteIngresso.setText("Deletar");
        deleteIngresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteIngressoMouseClicked(evt);
            }
        });
        deleteIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIngressoActionPerformed(evt);
            }
        });

        testbutton7.setText("Ingressos...");
        testbutton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testbutton7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel7.setText("Nome do Evento");

        entryNomeDoEvento.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        entryNomeDoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNomeDoEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cleanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteIngresso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryNomeDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(entryInstituicaoMeia)
                                .addComponent(entryCarteiraIdoso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(entryNumAssento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(entryPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(testbutton7))
                                .addComponent(entryTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(testbutton7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryNumAssento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryInstituicaoMeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryCarteiraIdoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryNomeDoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cleanButton)
                    .addComponent(changeButton)
                    .addComponent(deleteIngresso))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryNumAssentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNumAssentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNumAssentoActionPerformed

    private void entryInstituicaoMeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryInstituicaoMeiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryInstituicaoMeiaActionPerformed

    private void entryCarteiraIdosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryCarteiraIdosoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryCarteiraIdosoActionPerformed

    private void deleteIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIngressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteIngressoActionPerformed

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
        cadastrarIngresso();
    }//GEN-LAST:event_saveButtonMouseClicked

    private void testbutton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testbutton7MouseClicked
        infoGeraisIngressoForm infoIngr = new infoGeraisIngressoForm();
        infoIngr.fetchInfoIngresso();
        infoIngr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testbutton7MouseClicked

    private void cleanButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanButtonMouseDragged
        // TODdd your handling code here:
    }//GEN-LAST:event_cleanButtonMouseDragged

    private void cleanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanButtonMouseClicked
        entryPreco.setText("");
        entryNumAssento.setText("");
        entryInstituicaoMeia.setText("");
        entryCarteiraIdoso.setText("");
    }//GEN-LAST:event_cleanButtonMouseClicked

    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        buscaIngressoForm ingrInfo = new buscaIngressoForm();
        ingrInfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_changeButtonMouseClicked

    private void deleteIngressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteIngressoMouseClicked
        deletarIngresso(JOptionPane.showInputDialog(null, "Insira o código [ID] do ingresso.", "Alerta!", JOptionPane.INFORMATION_MESSAGE));
    }//GEN-LAST:event_deleteIngressoMouseClicked

    private void entryNomeDoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNomeDoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNomeDoEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingressoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingressoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingressoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingressoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingressoCadastroForm().setVisible(true);
            }
        });
    }
    
    public void cadastrarIngresso(){
        try{
            String cadastrar = "INSERT INTO Ingressos (preco, tipo, numeroAssento, instituicaoMeia, numCarteiraIdoso, nomeDoEvento) VALUES (?,?,?,?,?,?)";

            pst = conec.prepareStatement(cadastrar);

            pst.setString(1, entryPreco.getText());
            pst.setString(2, entryTipo.getSelectedItem().toString());
            pst.setString(3, entryNumAssento.getText());
            
            if(entryTipo.getSelectedItem().toString().equals("Meia") && !(entryInstituicaoMeia.getText().equals(""))){
                pst.setString(4, entryInstituicaoMeia.getText()); 
            } else {
                pst.setString(4, "N/A");
            }
            if(entryTipo.getSelectedItem().toString().equals("Meia") && !(entryCarteiraIdoso.getText().equals(""))){
                pst.setString(5, entryCarteiraIdoso.getText());
            } else{
                pst.setString(5, "N/A");
            }
            pst.setString(6, entryNomeDoEvento.getText());
     
            if(entryTipo.getSelectedItem().toString().equals("Meia") && (entryCarteiraIdoso.getText().equals("") && entryInstituicaoMeia.getText().equals(""))){
                throw new Exception("Se o ingresso for do tipo meia, é necessário uma Instituição ou número da Carteira de Idoso.");
            } else{
                pst.execute();
            }
            
            JOptionPane.showMessageDialog(null, "Ingresso adicionado com sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void deletarIngresso(String d){
        try{
            String deletar = "DELETE FROM Ingressos WHERE rowid = ? ";
            pst = conec.prepareStatement(deletar);
            pst.setString(1, d);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Ingresso deletado permanentememte!");
        
            } catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton deleteIngresso;
    private javax.swing.JTextField entryCarteiraIdoso;
    private javax.swing.JTextField entryInstituicaoMeia;
    private javax.swing.JTextField entryNomeDoEvento;
    private javax.swing.JTextField entryNumAssento;
    private javax.swing.JTextField entryPreco;
    private javax.swing.JComboBox<String> entryTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton testbutton7;
    // End of variables declaration//GEN-END:variables
}
